package com.radish.biyu.webapi.entity;

import java.util.Date;

public class TComment extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.id
     *
     * @mbggenerated Mon Sep 26 19:09:24 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.fid
     *
     * @mbggenerated Mon Sep 26 19:09:24 CST 2016
     */
    private Long fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.uid
     *
     * @mbggenerated Mon Sep 26 19:09:24 CST 2016
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.created
     *
     * @mbggenerated Mon Sep 26 19:09:24 CST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.comments
     *
     * @mbggenerated Mon Sep 26 19:09:24 CST 2016
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.id
     *
     * @return the value of t_comment.id
     *
     * @mbggenerated Mon Sep 26 19:09:24 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.id
     *
     * @param id the value for t_comment.id
     *
     * @mbggenerated Mon Sep 26 19:09:24 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.fid
     *
     * @return the value of t_comment.fid
     *
     * @mbggenerated Mon Sep 26 19:09:24 CST 2016
     */
    public Long getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.fid
     *
     * @param fid the value for t_comment.fid
     *
     * @mbggenerated Mon Sep 26 19:09:24 CST 2016
     */
    public void setFid(Long fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.uid
     *
     * @return the value of t_comment.uid
     *
     * @mbggenerated Mon Sep 26 19:09:24 CST 2016
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.uid
     *
     * @param uid the value for t_comment.uid
     *
     * @mbggenerated Mon Sep 26 19:09:24 CST 2016
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.created
     *
     * @return the value of t_comment.created
     *
     * @mbggenerated Mon Sep 26 19:09:24 CST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.created
     *
     * @param created the value for t_comment.created
     *
     * @mbggenerated Mon Sep 26 19:09:24 CST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.comments
     *
     * @return the value of t_comment.comments
     *
     * @mbggenerated Mon Sep 26 19:09:24 CST 2016
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.comments
     *
     * @param comments the value for t_comment.comments
     *
     * @mbggenerated Mon Sep 26 19:09:24 CST 2016
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Mon Sep 26 19:09:24 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fid=").append(fid);
        sb.append(", uid=").append(uid);
        sb.append(", created=").append(created);
        sb.append(", comments=").append(comments);
        sb.append("]");
        return sb.toString();
    }
}