package com.radish.biyu.webapi.entity;

import java.util.Date;

public class TFeed extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feed.id
     *
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feed.uid
     *
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feed.ftype
     *
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    private String ftype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feed.forwarded
     *
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    private Integer forwarded = 0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feed.liked
     *
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    private Integer liked = 0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feed.lng
     *
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    private String lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feed.lat
     *
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    private String lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feed.created
     *
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    private Date created;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feed.message
     *
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feed.pic
     *
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    private String pic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feed.id
     *
     * @return the value of t_feed.id
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feed.id
     *
     * @param id the value for t_feed.id
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feed.uid
     *
     * @return the value of t_feed.uid
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feed.uid
     *
     * @param uid the value for t_feed.uid
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feed.ftype
     *
     * @return the value of t_feed.ftype
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    public String getFtype() {
        return ftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feed.ftype
     *
     * @param ftype the value for t_feed.ftype
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    public void setFtype(String ftype) {
        this.ftype = ftype == null ? null : ftype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feed.forwarded
     *
     * @return the value of t_feed.forwarded
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    public Integer getForwarded() {
        return forwarded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feed.forwarded
     *
     * @param forwarded the value for t_feed.forwarded
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    public void setForwarded(Integer forwarded) {
        this.forwarded = forwarded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feed.liked
     *
     * @return the value of t_feed.liked
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    public Integer getLiked() {
        return liked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feed.liked
     *
     * @param liked the value for t_feed.liked
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    public void setLiked(Integer liked) {
        this.liked = liked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feed.lng
     *
     * @return the value of t_feed.lng
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feed.lng
     *
     * @param lng the value for t_feed.lng
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feed.lat
     *
     * @return the value of t_feed.lat
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feed.lat
     *
     * @param lat the value for t_feed.lat
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feed.created
     *
     * @return the value of t_feed.created
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feed.created
     *
     * @param created the value for t_feed.created
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feed.message
     *
     * @return the value of t_feed.message
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feed.message
     *
     * @param message the value for t_feed.message
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feed.pic
     *
     * @return the value of t_feed.pic
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feed.pic
     *
     * @param pic the value for t_feed.pic
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feed
     *
     * @mbggenerated Mon Sep 26 19:10:01 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", ftype=").append(ftype);
        sb.append(", forwarded=").append(forwarded);
        sb.append(", liked=").append(liked);
        sb.append(", lng=").append(lng);
        sb.append(", lat=").append(lat);
        sb.append(", message=").append(message);
        sb.append(", pic=").append(pic);
        sb.append(", created=").append(created);
        sb.append("]");
        return sb.toString();
    }
}